services:
  database:
    container_name: database
    image: mysql:8.0.33
    restart: always
    env_file:
      - .env # Use the .env file for environment variables
    environment:
      MYSQL_DATABASE: smartcontact
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_HOST: "%"
      MYSQL_PORT: 3307
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - smartnetwork
  smartcontact:
    image: "smartcontact:latest"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smartcontact
    restart: on-failure
    env_file:
      - .env # Use the .env file for environment variables
    ports:
      - "8080:8080"
    environment:
      - server.port=8080
      - spring.datasource.username=${DATABASE_USERNAME}
      - spring.datasource.password=${DATABASE_PASSWORD}
      - BOOK_DELIVERY_DB_IP=database
      - BOOK_DELIVERY_DB_PORT=3307
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3307/smartcontact
    depends_on:
      - database
    networks:
      - smartnetwork
networks:
  smartnetwork:
