spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345
    url: jdbc:mysql://localhost:3306/smartcontact
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 999999KB
      
      
server:
  error:
    whitelabel:
      enabled: false
    path: /error
    
mail:
  properties:
    username: demo_name
    password: password
    host: smtp.gmail.com
    port: 465
    ssl-enable: true
    auth: true
    starttls-enable: true
    ssl-trust: true
